<!-- <h4><?php  echo "Sold By- "?><a href=" <?php echo $block->getVendorUrl().'entity_id/'. $block->getVendorID() ?>"><?php echo $block->getVendorname() ?></a></h4> -->

<?php if($block->getVendorname()!='null'){?>
<?php
if($block->getVendorname() && $block->VendorEnable()){ ?>
<h4><?php  echo "Sold By- "?> <a href="<?php echo $block->getVendorUrl(). 'entity_id/' . $block->getVendorID() ?>"><?php echo $block->getVendorname()?></a></h4>
<?php } ?>
<?php } ?>


